### ISSUE TITLE
refactor the current codebase

### ISSUE THREAD

**Issue by gannebamm** [breedfides/airflow-etl#3]
# status quo

The current codebase is messy and is not DRY. Also, the setup instructions are convoluted.

# Expected behaviour

Refactor the codebase for better readability and DRY. Enable easy setup with a makefile.

**Comment by brightemahpixida** [comment]
Hi @gannebamm - thanks for adding this to the first Sprint, just to be sure on my end, are there adjustments you'd need me to make now on the Pull Request i raised.

Thanks,
Bright Emah

**Comment by gannebamm** [comment]
I have not tested it in full yet. But from what I see, it is okay. We just want to structure the Sprints better.
